utils.settings.get 
utils.settings.onLoad
utils.settings.update
utils.playlist.init
utils.playlist.getURI
utils.playlist.makeOffline
utils.playlist.shuffle.getHighest
utils.playlist.shuffle.createFolder
utils.playlist.shuffle.moveSplToFolder
utils.playlist.shuffle.newSpl
utils.migrate.whenDone
utils.migrate.fromURI
add.addTracks
add.getTracks
add.AlbumsFromArtist.fromLocal
add.AlbumsFromArtist
add.TracksFromAlbum.fromLocal
add.TracksFromAlbum
